spring:
  application:
    name: hello-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
---
spring:
  profiles: client1
server:
  port: 10001

---
spring:
  profiles: client2
server:
  port: 10003